In [5]:
import warnings
warnings.filterwarnings('ignore')

In [11]:
# Dependencies
import pytz
import datetime as dt
from datetime import datetime
import dateparser
import gmaps
import numpy as np
import pandas as pd
import requests
import time
from pprint import pprint 
from scipy.stats import linregress
import scipy.stats as stats
from matplotlib import pyplot as plt
import matplotlib.dates as mdates
from suntime import Sun, SunTimeException
import os
import json
import urllib.request

In [38]:
accident_data_to_load ="../../../Resources/US_Accidents_May19.csv"
df_raw = pd.read_csv(
    accident_data_to_load)

# Visualize
df_raw = df_raw.reset_index()
df_raw.set_index('ID', inplace=True)
df_raw.head()

,index,State,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,Number,...,Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Traffic_Signal,Sunrise_Sunset,Civil_Twilight,Astronomical_Twilight
ID,,,,,,,,,,,,,,,,,,,,,
A-1,0,OH,3,2/8/16 5:46,2/8/16 11:00,39.865147,-84.058723,0.01,Right lane blocked due to accident on I-70 Eas...,NaN,...,29.68,10.0,Calm,NaN,0.02,Light Rain,False,Night,Night,Night
A-2,1,OH,2,2/8/16 6:07,2/8/16 6:37,39.928059,-82.831184,0.01,Accident on Brice Rd at Tussing Rd. Expect del...,2584.0,...,29.65,10.0,Calm,NaN,0.00,Light Rain,False,Night,Night,Day
A-3,2,OH,2,2/8/16 6:49,2/8/16 7:19,39.063148,-84.032608,0.01,Accident on OH-32 State Route 32 Westbound at ...,NaN,...,29.67,10.0,SW,3.5,NaN,Overcast,True,Night,Night,Day
A-4,3,OH,3,2/8/16 7:23,2/8/16 7:53,39.747753,-84.205582,0.01,Accident on I-75 Southbound at Exits 52 52B US...,NaN,...,29.64,9.0,SW,4.6,NaN,Mostly Cloudy,False,Night,Day,Day
A-5,4,OH,2,2/8/16 7:39,2/8/16 8:09,39.627781,-84.188354,0.01,Accident on McEwen Rd at OH-725 Miamisburg Cen...,NaN,...,29.65,6.0,SW,3.5,NaN,Mostly Cloudy,True,Day,Day,Day

In [39]:
df_raw.columns

Index(['index', 'State', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'Distance(mi)', 'Description', 'Number', 'Street', 'Side',
       'City', 'County', 'Zipcode', 'Country', 'Timezone', 'Airport_Code',
       'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)',
       'Pressure(in)', 'Visibility(mi)', 'Wind_Direction', 'Wind_Speed(mph)',
       'Precipitation(in)', 'Weather_Condition', 'Traffic_Signal',
       'Sunrise_Sunset', 'Civil_Twilight', 'Astronomical_Twilight'],
      dtype='object')

In [42]:
df=df_raw.drop(columns=['index', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'Distance(mi)', 'Description', 'Number', 'Street', 'Side',
       'City', 'County', 'Zipcode', 'Country', 'Timezone', 'Airport_Code', 
        'Weather_Timestamp', 'Civil_Twilight', 'Astronomical_Twilight','Traffic_Signal' ])

In [43]:
df.head()

,State,Severity,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Sunrise_Sunset
ID,,,,,,,,,,,,
A-1,OH,3,36.9,NaN,91.0,29.68,10.0,Calm,NaN,0.02,Light Rain,Night
A-2,OH,2,37.9,NaN,100.0,29.65,10.0,Calm,NaN,0.00,Light Rain,Night
A-3,OH,2,36.0,33.3,100.0,29.67,10.0,SW,3.5,NaN,Overcast,Night
A-4,OH,3,35.1,31.0,96.0,29.64,9.0,SW,4.6,NaN,Mostly Cloudy,Night
A-5,OH,2,36.0,33.3,89.0,29.65,6.0,SW,3.5,NaN,Mostly Cloudy,Day

In [44]:
weather_dict = {'Clear':"Dry_Conditions", 'Overcast':"Dry_Conditions", 'Mostly Cloudy':"Dry_Conditions", 'Partly Cloudy':"Dry_Conditions", 'Scattered Clouds':"Dry_Conditions",
                'Rain':"Rainy_Conditions", 'Light Rain':"Rainy_Conditions", 'Rain Showers':"Rainy_Conditions", 'Light Rain Showers':"Rainy_Conditions", 'Heavy Drizzle':"Rainy_Conditions",
                    'Light Freezing Rain':"Rainy_Conditions", 'Drizzle':"Rainy_Conditions", 'Thunderstorms and Rain':"Rainy_Conditions", 'Heavy Thunderstorms and Rain':"Rainy_Conditions",
                    'Light Drizzle':"Rainy_Conditions", 'Thunderstorm':"Rainy_Conditions", 'Light Thunderstorms and Rain':"Rainy_Conditions", 'Ice Pellets':'Freezing_Conditions','Light Ice Pellets':'Freezing_Conditions', 
                'Blowing Snow':'Freezing_Conditions', 'Heavy Snow':'Freezing_Conditions', 'Snow':'Freezing_Conditions', 'Light Snow':'Freezing_Conditions', 
                'Sand':"Foggy_Conditions", 'Haze':"Foggy_Conditions", 'Fog':"Foggy_Conditions", 'Smoke':"Foggy_Conditions", 'Mist':"Foggy_Conditions", 'Patches of Fog':"Foggy_Conditions", 'Shallow Fog':"Foggy_Conditions", 'Widespread Dust':"Foggy_Conditions", 
                   'Volcanic Ash':"Foggy_Conditions"}

In [45]:
df['Weather_Condition_Summary']=df['Weather_Condition'].map(weather_dict)

In [46]:
df.head()

,State,Severity,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Sunrise_Sunset,Weather_Condition_Summary
ID,,,,,,,,,,,,,
A-1,OH,3,36.9,NaN,91.0,29.68,10.0,Calm,NaN,0.02,Light Rain,Night,Rainy_Conditions
A-2,OH,2,37.9,NaN,100.0,29.65,10.0,Calm,NaN,0.00,Light Rain,Night,Rainy_Conditions
A-3,OH,2,36.0,33.3,100.0,29.67,10.0,SW,3.5,NaN,Overcast,Night,Dry_Conditions
A-4,OH,3,35.1,31.0,96.0,29.64,9.0,SW,4.6,NaN,Mostly Cloudy,Night,Dry_Conditions
A-5,OH,2,36.0,33.3,89.0,29.65,6.0,SW,3.5,NaN,Mostly Cloudy,Day,Dry_Conditions

In [47]:
df['Weather_Condition_Summary'].value_counts()

Dry_Conditions         900644
Rainy_Conditions        74510
Foggy_Conditions        23425
Freezing_Conditions     15893
Name: Weather_Condition_Summary, dtype: int64

In [48]:
os.makedirs(os.path.join('output_data'),exist_ok=True)

In [57]:
fig, ax = plt.subplots(figsize=(20,14))
df['Weather_Condition_Summary'].value_counts().sort_values(ascending=False).plot.bar(width=0.5,edgecolor='k',align='center',linewidth=2)
plt.xlabel('Weather Condition',fontsize=20)
plt.ylabel('Number of Accidents',fontsize=20)
ax.tick_params(labelsize=20)
plt.title('Accidents by Weather Condition',fontsize=25)
plt.xticks(rotation=0)

#plt.show()
plt.savefig(os.path.join('output_data',f'accidents_by_weather_condition_bar.png'))

In [50]:
df['Weather_Condition_Summary'].value_counts().index

Index(['Dry_Conditions', 'Rainy_Conditions', 'Foggy_Conditions',
       'Freezing_Conditions'],
      dtype='object')

In [30]:
#Gmap of each accident

In [51]:
df_raw.head()

,index,State,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,Number,...,Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Traffic_Signal,Sunrise_Sunset,Civil_Twilight,Astronomical_Twilight
ID,,,,,,,,,,,,,,,,,,,,,
A-1,0,OH,3,2/8/16 5:46,2/8/16 11:00,39.865147,-84.058723,0.01,Right lane blocked due to accident on I-70 Eas...,NaN,...,29.68,10.0,Calm,NaN,0.02,Light Rain,False,Night,Night,Night
A-2,1,OH,2,2/8/16 6:07,2/8/16 6:37,39.928059,-82.831184,0.01,Accident on Brice Rd at Tussing Rd. Expect del...,2584.0,...,29.65,10.0,Calm,NaN,0.00,Light Rain,False,Night,Night,Day
A-3,2,OH,2,2/8/16 6:49,2/8/16 7:19,39.063148,-84.032608,0.01,Accident on OH-32 State Route 32 Westbound at ...,NaN,...,29.67,10.0,SW,3.5,NaN,Overcast,True,Night,Night,Day
A-4,3,OH,3,2/8/16 7:23,2/8/16 7:53,39.747753,-84.205582,0.01,Accident on I-75 Southbound at Exits 52 52B US...,NaN,...,29.64,9.0,SW,4.6,NaN,Mostly Cloudy,False,Night,Day,Day
A-5,4,OH,2,2/8/16 7:39,2/8/16 8:09,39.627781,-84.188354,0.01,Accident on McEwen Rd at OH-725 Miamisburg Cen...,NaN,...,29.65,6.0,SW,3.5,NaN,Mostly Cloudy,True,Day,Day,Day

In [53]:
plt.scatter(df_raw['Start_Lng'], df_raw['Start_Lat'], s=df_raw['Severity'])
#plt.show()
plt.savefig(os.path.join('output_data',f'scatter plot of accidents.png'))

In [55]:
labels=df['Weather_Condition_Summary'].value_counts().index
plt.figure(figsize=(10,8))
plt.pie(df['Weather_Condition_Summary'].value_counts(), labels=labels, wedgeprops={'linewidth':3}, explode=(0.2,0.1,0.1,0.1),
       shadow=False, autopct='%1.1f%%',pctdistance=.65, labeldistance=1.1, startangle=25, textprops={'fontsize': 14})
plt.axis("equal")
plt.title('Accidents by Weather Condition',fontsize=25)
plt.savefig(os.path.join('output_data',f'accidents by weather condition pie chart.png'))
#plt.show()